services:

  mysql:
    image: mysql:8.0
    
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    
    ports:
      - "3307:3306"
    
    environment:
      MYSQL_DATABASE: stockdata
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Taipei
    
    volumes:
      - mysql:/var/lib/mysql
    
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    
    depends_on:
      - mysql
    
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: test
    
    networks:
      - dev

  stockdata_api:
    image: stockdata_api
    
    ports:
      - "8888:8888"
    
    depends_on:
      - mysql
    
    environment:
      MYSQL_DATA_HOST: mysql
      MYSQL_DATA_USER: root
      MYSQL_DATA_PASSWORD: test
      MYSQL_DATA_PORT: 3306
      MYSQL_DATA_DATABASE: stockdata
    
    networks:
      - dev
    
    restart: unless-stopped

  stockdata_crawler:
    
    image: stockdata_crawler
    
    depends_on:
      - mysql
    
    environment:
      MYSQL_DATA_HOST: mysql
      MYSQL_DATA_USER: user
      MYSQL_DATA_PASSWORD: test
      MYSQL_DATA_PORT: 3306
      MYSQL_DATA_DATABASE: stockdata
    
    networks:
      - dev

networks:
  dev:

volumes:
  mysql:
   external: true


