services:

  mysql:
    
    image: mysql:8.0
    
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    
    ports:
      - "3307:3306"
    
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Taipei
    
    volumes:
      - mysql:/var/lib/mysql
    
    networks:
      - dev

  phpmyadmin:
    
    image: phpmyadmin/phpmyadmin:latest
    
    ports:
      - "8000:80"
    
    depends_on:
      - mysql
    
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: test
    
    networks:
      - dev

networks:
  dev:

volumes:
  mysql:
    external: true
