services:
  mysql:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Taipei
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - dev
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - node.role == manager

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - dev
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      - MYSQLD_EXPORTER_DATA_SOURCE_NAME=${MYSQL_USER}:${MYSQL_PASSWORD}@(mysql:3306)/
    depends_on:
      - mysql
    command:
      - "--mysqld.address=mysql:3306"
      - "--mysqld.username=${MYSQL_USER}"
    networks:
      - dev
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  stockdata-api:
    image: stockdata_api
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      MYSQL_DATA_HOST: ${MYSQL_HOST}
      MYSQL_DATA_USER: ${MYSQL_USER}
      MYSQL_DATA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATA_PORT: ${MYSQL_PORT}
      MYSQL_DATA_DATABASE: ${MYSQL_DATABASE}
    networks:
      - dev
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  dev:
    external: true

volumes:
  mysql:
    external: true