services:

  mysql:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Taipei
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - dev

  stockdata_api:
    image: stockdata_api
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      MYSQL_DATA_HOST: ${MYSQL_HOST}
      MYSQL_DATA_USER: ${MYSQL_USER}
      MYSQL_DATA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATA_PORT: ${MYSQL_PORT}
      MYSQL_DATA_DATABASE: ${MYSQL_DATABASE}
    networks:
      - dev
    restart: unless-stopped

networks:
  dev:
    external: true

volumes:
  mysql:
    external: true
