{
 "title": "Stockdata Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HardWares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU (%)"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "RAM (%)"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 1)", "legendFormat": "service numbers" },
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Airflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat[1m])",
     "legendFormat": "airflow heart rate"
    }
   ]
  },
  {
   "title": "API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"stockdata-api\"}[5m])",
     "legendFormat": "QPS"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"stockdata-api\"}[5m]))",
     "legendFormat": "API response time P50"
    }
   ]
  }
 ]
}